[package]
name = "rpm"
version = "0.1.0"
authors = ["paul-hanneforth <paul.hanneforth.o@gmail.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.5.1"